mod probes;

use degu_core::ecosystem::{DetectCtx, ScanOutcome};
use degu_core::finding::{FindingKind, Ownership, Recovery, RegenCost};
use std::path::Path;

pub(crate) use probes::{ArtifactClassification, classify};

const BUILD_RATIONALE: &str = "build artifacts are regenerated by the next build or install; deleting costs rebuild time, not data";
const WEAK_BUILD_RATIONALE: &str = "directory structure suggests build or bytecode cache storage, but the available evidence does not establish that every entry is regenerable";
const TAG_RATIONALE: &str = "CACHEDIR.TAG identifies cache storage but does not establish its recovery cost, ownership, or coordination requirements";
pub const SOURCE_ID: &str = "artifacts";

#[derive(Clone, Copy)]
pub(crate) enum ArtifactEvidence {
    BuildStructure,
    WeakBuildStructure,
    CacheTag,
}

pub(crate) fn finding_for(path: &Path, ctx: &DetectCtx, evidence: ArtifactEvidence) -> ScanOutcome {
    let (kind, recovery, ownership, rationale) = facts_for(evidence);
    crate::measure_finding(
        path,
        ctx,
        crate::FindingSpec {
            ecosystem: SOURCE_ID,
            kind,
            facts: (recovery, ownership, None),
            rationale,
        },
    )
}

fn facts_for(evidence: ArtifactEvidence) -> (FindingKind, Recovery, Ownership, &'static str) {
    match evidence {
        ArtifactEvidence::BuildStructure => (
            FindingKind::BuildArtifact,
            Recovery::Regenerable {
                cost: RegenCost::Cheap,
            },
            Ownership::Standalone,
            BUILD_RATIONALE,
        ),
        ArtifactEvidence::WeakBuildStructure => (
            FindingKind::Other,
            Recovery::Unknown,
            Ownership::Unknown,
            WEAK_BUILD_RATIONALE,
        ),
        ArtifactEvidence::CacheTag => (
            FindingKind::Other,
            Recovery::Unknown,
            Ownership::Unknown,
            TAG_RATIONALE,
        ),
    }
}
