use degu_core::ecosystem::{DetectCtx, Ecosystem, Relocation, Root, RootOutcome, ScanOutcome};
use degu_core::finding::{FindingFacts, FindingKind, Ownership, Recovery, RegenCost};
use std::ffi::CStr;
use std::mem::MaybeUninit;
use std::path::{Path, PathBuf};
use std::{fs, io};

const RATIONALE: &str = "PyTorch Inductor cache in temp storage; regenerated by compilation, and Triton artifacts often live inside it";
const USER_ENV_ORDER: [&str; 4] = ["LOGNAME", "USER", "LNAME", "USERNAME"];
const TEMP_ENV_ORDER: [&str; 3] = ["TMPDIR", "TEMP", "TMP"];
const UNIX_TEMP_DEFAULTS: [&str; 3] = ["/tmp", "/var/tmp", "/usr/tmp"];
const MIN_PASSWD_BUFFER_BYTES: usize = 1024;

pub struct Inductor;

impl Ecosystem for Inductor {
    fn id(&self) -> &'static str {
        "inductor"
    }

    fn roots(&self, ctx: &DetectCtx) -> RootOutcome {
        if ctx.deadline_elapsed() {
            return truncated_roots(false);
        }
        if let Some(dir) = ctx.env("TORCHINDUCTOR_CACHE_DIR") {
            return crate::resolve_existing_roots(
                ctx,
                self.id(),
                vec![Root::redirect(
                    "TORCHINDUCTOR_CACHE_DIR",
                    PathBuf::from(dir),
                )],
            );
        }
        let (user, user_incomplete) = default_username(ctx);
        let Some(user) = user else {
            return truncated_roots(user_incomplete);
        };
        if ctx.deadline_elapsed() {
            return truncated_roots(user_incomplete);
        }
        let (base, base_incomplete) = python_temp_base(ctx);
        if ctx.deadline_elapsed() {
            return truncated_roots(user_incomplete || base_incomplete);
        }
        let Some(base) = base else {
            return RootOutcome::failed();
        };
        let mut outcome = crate::resolve_existing_roots(
            ctx,
            self.id(),
            vec![Root::well_known(base.join(format!("torchinductor_{user}")))],
        );
        outcome.incomplete |= user_incomplete || base_incomplete;
        outcome
    }

    fn relocations(&self) -> Vec<Relocation> {
        vec![Relocation {
            var: "TORCHINDUCTOR_CACHE_DIR",
            subdir: "torchinductor",
        }]
    }

    fn stated_facts(&self, _root: &Root) -> FindingFacts {
        (
            Recovery::Regenerable {
                cost: RegenCost::Costly,
            },
            Ownership::Standalone,
            None,
        )
    }

    fn scan(&self, root: &Root, ctx: &DetectCtx) -> ScanOutcome {
        crate::measure_finding(
            &root.path,
            ctx,
            crate::FindingSpec {
                ecosystem: self.id(),
                kind: FindingKind::BuildArtifact,
                facts: self.stated_facts(root),
                rationale: RATIONALE,
            },
        )
    }
}

fn default_username(ctx: &DetectCtx) -> (Option<String>, bool) {
    let mut incomplete = false;
    for key in USER_ENV_ORDER {
        if ctx.deadline_elapsed() {
            return (None, incomplete);
        }
        let Some(value) = ctx.env(key) else {
            continue;
        };
        if let Some(username) = value.to_str() {
            return (Some(sanitize_username(username)), incomplete);
        }
        tracing::warn!(
            variable = key,
            "account name environment value is not valid UTF-8"
        );
        incomplete = true;
    }
    if ctx.deadline_elapsed() {
        return (None, incomplete);
    }
    let (username, lookup_incomplete) = system_username();
    (
        Some(sanitize_username(&username)),
        incomplete || lookup_incomplete,
    )
}

fn python_temp_base(ctx: &DetectCtx) -> (Option<PathBuf>, bool) {
    let mut candidates = Vec::new();
    let mut incomplete = false;
    for variable in TEMP_ENV_ORDER {
        if ctx.deadline_elapsed() {
            return (None, incomplete);
        }
        let Some(base) = ctx.env(variable) else {
            continue;
        };
        let root = Root::redirect(variable, PathBuf::from(base));
        if crate::validate_root_path(ctx, "inductor", &root) {
            candidates.push(root.path);
        } else {
            incomplete = true;
        }
    }
    candidates.extend(UNIX_TEMP_DEFAULTS.map(PathBuf::from));
    if ctx.deadline_elapsed() {
        return (None, incomplete);
    }
    match std::env::current_dir() {
        Ok(path) => candidates.push(path),
        Err(error) => {
            tracing::warn!(%error, "failed to resolve Python's final temporary-directory candidate");
            incomplete = true;
        }
    }
    for base in candidates {
        if ctx.deadline_elapsed() {
            return (None, incomplete);
        }
        match usable_temp_base(&base, ctx) {
            Ok(TempBaseProbe::Usable) => return (Some(base), incomplete),
            Ok(TempBaseProbe::Unusable) => {}
            Ok(TempBaseProbe::Deadline) => return (None, incomplete),
            Err(error) => {
                tracing::warn!(base = %base.display(), %error, "Python temporary-directory probe failed");
                incomplete = true;
            }
        }
    }
    tracing::warn!("no usable Python temporary-directory candidate found");
    (None, true)
}

enum TempBaseProbe {
    Usable,
    Unusable,
    Deadline,
}

fn usable_temp_base(base: &Path, ctx: &DetectCtx) -> io::Result<TempBaseProbe> {
    match fs::metadata(base) {
        Ok(metadata) if metadata.is_dir() => {}
        Ok(_) => return Ok(TempBaseProbe::Unusable),
        Err(error) if crate::is_missing_path_error(&error) => {
            return Ok(TempBaseProbe::Unusable);
        }
        Err(error) => return Err(error),
    }
    if ctx.deadline_elapsed() {
        return Ok(TempBaseProbe::Deadline);
    }
    let access = rustix::fs::Access::WRITE_OK | rustix::fs::Access::EXEC_OK;
    match rustix::fs::access(base, access) {
        Ok(()) => Ok(TempBaseProbe::Usable),
        Err(
            rustix::io::Errno::ACCESS
            | rustix::io::Errno::NOENT
            | rustix::io::Errno::NOTDIR
            | rustix::io::Errno::ROFS,
        ) => Ok(TempBaseProbe::Unusable),
        Err(error) => Err(io::Error::from_raw_os_error(error.raw_os_error())),
    }
}

fn system_username() -> (String, bool) {
    let uid = rustix::process::getuid().as_raw();
    match passwd_username(uid) {
        Ok(Some(username)) => (username, false),
        Ok(None) => {
            tracing::warn!(
                uid,
                "account name is unavailable; using PyTorch's UID fallback"
            );
            (format!("uid_{uid}"), true)
        }
        Err(error) => {
            tracing::warn!(
                uid,
                error,
                "account lookup failed; using PyTorch's UID fallback"
            );
            (format!("uid_{uid}"), true)
        }
    }
}

fn passwd_username(uid: libc::uid_t) -> Result<Option<String>, i32> {
    // SAFETY: querying the recommended reentrant passwd buffer size has no pointer arguments.
    let suggested = unsafe { libc::sysconf(libc::_SC_GETPW_R_SIZE_MAX) };
    let mut buffer = vec![
        0_u8;
        usize::try_from(suggested)
            .unwrap_or(MIN_PASSWD_BUFFER_BYTES)
            .max(MIN_PASSWD_BUFFER_BYTES)
    ];
    loop {
        let mut entry = MaybeUninit::<libc::passwd>::uninit();
        let mut result = std::ptr::null_mut();
        // SAFETY: entry, result, and buffer remain valid for the call; getpwuid_r initializes entry on success.
        let status = unsafe {
            libc::getpwuid_r(
                uid,
                entry.as_mut_ptr(),
                buffer.as_mut_ptr().cast(),
                buffer.len(),
                &mut result,
            )
        };
        if status == libc::ERANGE {
            let capacity = buffer.len().checked_mul(2).ok_or(libc::ENOMEM)?;
            buffer.resize(capacity, 0);
            continue;
        }
        if status != 0 {
            return Err(status);
        }
        if result.is_null() {
            return Ok(None);
        }
        // SAFETY: successful getpwuid_r initialized entry and returned its address in result.
        let entry = unsafe { entry.assume_init() };
        if entry.pw_name.is_null() {
            return Err(libc::EINVAL);
        }
        // SAFETY: pw_name points into buffer, which remains alive, and getpwuid_r returns a C string.
        let username = unsafe { CStr::from_ptr(entry.pw_name) };
        return username
            .to_str()
            .map(|value| Some(value.to_owned()))
            .map_err(|_| libc::EILSEQ);
    }
}

fn truncated_roots(incomplete: bool) -> RootOutcome {
    RootOutcome {
        incomplete,
        truncated: true,
        ..RootOutcome::default()
    }
}

fn sanitize_username(username: &str) -> String {
    username
        .chars()
        .map(|character| match character {
            '\\' | '/' | ':' | '*' | '?' | '"' | '<' | '>' | '|' => '_',
            _ => character,
        })
        .collect()
}
